// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lggxdhktiydplorjhaxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZ3hkaGt0aXlkcGxvcmpoYXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNTM2MTEsImV4cCI6MjA3NTkyOTYxMX0.RbUBYlDDd_j8C7p66kEudtevJMJE7Figoh56aVJLHGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});